# clash-config.yaml
# é€šç”¨é…ç½®
port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'

# ä»£ç†èŠ‚ç‚¹ (Proxies)
proxies:
  - name: "Singapore"
    type: vless
    server: 154.204.183.76
    port: 17452
    uuid: 2e3f782a-ea61-441e-ead3-0030c5175cbc
    network: tcp
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    servername: www.yahoo.com
    reality-opts:
      public-key: wF-z2UIiSifCZjfW-0XAs1qZ814r1cgSW4F0fHJOEhM
      short-id: '649b0624'
      
  - name: "JP West"
    type: vless
    server: 20.27.217.205
    port: 32750
    uuid: 6ae92e65-909b-42ad-8bd3-ea632e39d0d0
    network: tcp
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    servername: apple.com
    reality-opts:
      public-key: 6dtOUsEp-TvgExYIkTWdi9zj7D1UsYruv9SEVFcNRVU
      short-id: '81ec2e21'

  - name: "HK"
    type: vless
    server: 13.94.28.228
    port: 57189
    uuid: ab8eff5a-1fee-4bd9-ae33-87be305853cb
    network: tcp
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    servername: apple.com
    reality-opts:
      public-key: QKUDh_N-FSbpjGk9ip6JCAAHsUBWWhrZ5--uyrmtR34
      short-id: '85a6ef28'
      
  - name: "US West"
    type: vless
    server: 20.171.45.64
    port: 37948
    uuid: 7e17c550-891a-49d6-f1b9-60b4dce68c78
    network: tcp
    tls: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome
    servername: apple.com
    reality-opts:
      public-key: k3Hk8OHbi8vq4OrmwW9CPundNGjWsrmgxeFCMZ_OxQA
      short-id: '9054d0af'

# ä»£ç†ç»„ (Proxy Groups)
proxy-groups:
  - name: "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
    type: select
    proxies:
      - "Singapore"
      - "JP West"
      - "HK"
      - "US West"
      
  - name: "â™»ï¸ è‡ªåŠ¨æµ‹é€Ÿ"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "Singapore"
      - "JP West"
      - "HK"
      - "US West"      

# è§„åˆ™ (Rules)
# åœ¨å…¨å±€æ¨¡å¼ä¸‹ï¼Œä»¥ä¸‹è§„åˆ™ä¸ä¼šç”Ÿæ•ˆã€‚
rules:
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
